@TechChallenge__Measurements__Api_HostAddress = http://localhost:5153
@userId = alpha

GET {{TechChallenge__Measurements__Api_HostAddress}}/measurements/{{userId}}?from=10&to=100
Accept: application/json

###
